name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Run tests with pytest
      run: |
        pytest tests/ -v --cov=src --cov-report=xml
    
    - name: Run log analyzer test
      run: |
        python -c "
        from src.log_analyzer import LogAnalyzer
        analyzer = LogAnalyzer()
        result = analyzer.analyze_ci_logs('ERROR: Test failed\\nWARNING: Deprecated API')
        print('Test completed successfully')
        print(f'Errors: {result[\"error_count\"]}, Warnings: {result[\"warning_count\"]}')
        "
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          test_results/
          logs/
        if-no-files-found: ignore

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Deploy to Render
      run: |
        echo "Deploying to Render..."
        echo "Render will automatically deploy when changes are pushed to main branch"
